### ISSUE TITLE
Request to Add License

### ISSUE THREAD

**Issue by wthe2004** [shaunferns26/Kinect-Archery-Game#2]
Hi Shaun-Fernandes,

I noticed that your repository lacks a license. Would you consider adding one to clarify how others can use and distribute your code?

Thanks!

**Comment by Shaun-Fernandes** [comment]
Hi @goodmorning-hwt,

Thanks for reaching out. 
I've added an MIT license to the project, so please feel free to use it however you'd like.

**Comment by wthe2004** [comment]
Thank you very much!
